# @package eval.json_unlearn.metrics.forget_Q_A_Prob
defaults:
  - ../../data/datasets@datasets: JSON_QA_eval_forget
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: probability
batch_size: ${eval.json_unlearn.batch_size}

datasets:
  JSON_QA_eval_forget:
    args:
      hf_args:
        data_files: ${eval.json_unlearn.eval_data_dir}/eval_forget.jsonl
      question_key: ${eval.json_unlearn.question_key}
